const data = [
  {
    login: "brad",
    id: 1614,
    node_id: "MDQ6VXNlcjE2MTQ=",
    avatar_url: "https://avatars.githubusercontent.com/u/1614?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/brad",
    html_url: "https://github.com/brad",
    followers_url: "https://api.github.com/users/brad/followers",
    following_url: "https://api.github.com/users/brad/following{/other_user}",
    gists_url: "https://api.github.com/users/brad/gists{/gist_id}",
    starred_url: "https://api.github.com/users/brad/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/brad/subscriptions",
    organizations_url: "https://api.github.com/users/brad/orgs",
    repos_url: "https://api.github.com/users/brad/repos",
    events_url: "https://api.github.com/users/brad/events{/privacy}",
    received_events_url: "https://api.github.com/users/brad/received_events",
    type: "User",
    site_admin: false,
    score: 1,
  },
  {
    login: "bradtraversy",
    id: 5550850,
    node_id: "MDQ6VXNlcjU1NTA4NTA=",
    avatar_url: "https://avatars.githubusercontent.com/u/5550850?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/bradtraversy",
    html_url: "https://github.com/bradtraversy",
    followers_url: "https://api.github.com/users/bradtraversy/followers",
    following_url:
      "https://api.github.com/users/bradtraversy/following{/other_user}",
    gists_url: "https://api.github.com/users/bradtraversy/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/bradtraversy/starred{/owner}{/repo}",
    subscriptions_url:
      "https://api.github.com/users/bradtraversy/subscriptions",
    organizations_url: "https://api.github.com/users/bradtraversy/orgs",
    repos_url: "https://api.github.com/users/bradtraversy/repos",
    events_url: "https://api.github.com/users/bradtraversy/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/bradtraversy/received_events",
    type: "User",
    site_admin: false,
    score: 1,
  },
  {
    login: "bradfitz",
    id: 2621,
    node_id: "MDQ6VXNlcjI2MjE=",
    avatar_url: "https://avatars.githubusercontent.com/u/2621?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/bradfitz",
    html_url: "https://github.com/bradfitz",
    followers_url: "https://api.github.com/users/bradfitz/followers",
    following_url:
      "https://api.github.com/users/bradfitz/following{/other_user}",
    gists_url: "https://api.github.com/users/bradfitz/gists{/gist_id}",
    starred_url: "https://api.github.com/users/bradfitz/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/bradfitz/subscriptions",
    organizations_url: "https://api.github.com/users/bradfitz/orgs",
    repos_url: "https://api.github.com/users/bradfitz/repos",
    events_url: "https://api.github.com/users/bradfitz/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/bradfitz/received_events",
    type: "User",
    site_admin: false,
    score: 1,
  },
  {
    login: "kairess",
    id: 5242555,
    node_id: "MDQ6VXNlcjUyNDI1NTU=",
    avatar_url: "https://avatars.githubusercontent.com/u/5242555?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/kairess",
    html_url: "https://github.com/kairess",
    followers_url: "https://api.github.com/users/kairess/followers",
    following_url:
      "https://api.github.com/users/kairess/following{/other_user}",
    gists_url: "https://api.github.com/users/kairess/gists{/gist_id}",
    starred_url: "https://api.github.com/users/kairess/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/kairess/subscriptions",
    organizations_url: "https://api.github.com/users/kairess/orgs",
    repos_url: "https://api.github.com/users/kairess/repos",
    events_url: "https://api.github.com/users/kairess/events{/privacy}",
    received_events_url: "https://api.github.com/users/kairess/received_events",
    type: "User",
    site_admin: false,
    score: 1,
  },
  {
    login: "bradfrost",
    id: 383701,
    node_id: "MDQ6VXNlcjM4MzcwMQ==",
    avatar_url: "https://avatars.githubusercontent.com/u/383701?v=4",
    gravatar_id: "",
    url: "https://api.github.com/users/bradfrost",
    html_url: "https://github.com/bradfrost",
    followers_url: "https://api.github.com/users/bradfrost/followers",
    following_url:
      "https://api.github.com/users/bradfrost/following{/other_user}",
    gists_url: "https://api.github.com/users/bradfrost/gists{/gist_id}",
    starred_url:
      "https://api.github.com/users/bradfrost/starred{/owner}{/repo}",
    subscriptions_url: "https://api.github.com/users/bradfrost/subscriptions",
    organizations_url: "https://api.github.com/users/bradfrost/orgs",
    repos_url: "https://api.github.com/users/bradfrost/repos",
    events_url: "https://api.github.com/users/bradfrost/events{/privacy}",
    received_events_url:
      "https://api.github.com/users/bradfrost/received_events",
    type: "User",
    site_admin: false,
    score: 1,
  },
]
export default data
